# Generated by Django 2.2.6 on 2019-11-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FloreriaPetalos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
                ('desc', models.TextField(max_length=400)),
                ('estado', models.CharField(max_length=15)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
