# Generated by Django 2.2.6 on 2019-11-19 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FloreriaPetalos', '0004_remove_producto_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
