# Generated by Django 2.2.6 on 2019-11-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FloreriaPetalos', '0005_delete_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('valor', models.IntegerField(default=1000)),
                ('descripcion', models.TextField()),
                ('stock', models.IntegerField(default=1)),
            ],
        ),
    ]
