# Generated by Django 2.2.6 on 2019-12-03 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FloreriaPetalos', '0007_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('nombre_estado', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.ForeignKey(default='Disponible', on_delete=django.db.models.deletion.CASCADE, to='FloreriaPetalos.Estado'),
            preserve_default=False,
        ),
    ]
