# Generated by Django 2.2.6 on 2019-12-03 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FloreriaPetalos', '0008_auto_20191203_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='estado',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
