# Generated by Django 2.2.6 on 2019-12-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FloreriaPetalos', '0011_auto_20191203_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='Sin descripción.', null='Sin descripción.'),
        ),
    ]
