# Generated by Django 2.2.6 on 2019-12-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FloreriaPetalos', '0018_auto_20191208_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=400),
        ),
    ]
