# Generated by Django 2.2.6 on 2019-12-08 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FloreriaPetalos', '0021_auto_20191208_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
