# Generated by Django 2.2.6 on 2019-12-08 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FloreriaPetalos', '0023_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
